### ISSUE TITLE
Options in filter and on form page view not showing clickable.[Refined-filter-dropdown & Form-page-view]

### ISSUE THREAD

**Issue by Bhagyashrimane** [MetagaussInc/Blazeforms-Revamped-Frontend#73]
Options in the refined filter not showing clickable.
e.g. Folders, All forms. Starred, Archived, Build, Publish, Entries, URL, Permission, Delete, Move, Archive, Form Name, Edit, Filter.
Check here-
![image](https://user-images.githubusercontent.com/77260614/131319269-3baf5f6c-9f52-404d-ab22-1337b35daaab.png)

![image](https://user-images.githubusercontent.com/77260614/131320165-7c775671-86ec-4fa2-b2cc-8910b654292c.png)

**Comment by mJawed** [comment]
Fixed.

**Comment by Bhagyashrimane** [comment]
These options not showing clickable
1. Folders & sub-folders showing in the filter- On the form view page 
2. Checkboxes in front of the forms
3. Expand the link of the forms shown below the folder.
Check here-
![image](https://user-images.githubusercontent.com/77260614/132199578-302eece6-8049-470b-9b0b-7f07b44e44e5.png)

**Comment by mJawed** [comment]
Added cursor checkbox and filter arrow

**Comment by Bhagyashrimane** [comment]
![image](https://user-images.githubusercontent.com/77260614/132471268-6fb29a18-48fd-4c48-86c4-9e6704d27fcd.png)
 Black color underlined option still not showing clickable.

**Comment by mJawed** [comment]
Fixed.

**Comment by charan-singh05** [comment]
Issue fix verified.
